#!/bin/bash
# Run SSAM in parallel.
#
# Usage:
#   ./run_SSAM.sh                 # submit 4×20 block jobs: A/B/C/all, 20 blocks of 10 seeds each
#   sbatch run_SSAM.sh A          # run all 200 seeds for scenario A in one job
#   sbatch run_SSAM.sh A 3        # run block 3 (seeds 21–30) for scenario A in one job
#
# Each block job runs: python run_SSAM.py --job JOB --block BLOCK
# After all blocks finish, run a final aggregation job (no --block) to compute metrics:
#   sbatch run_SSAM.sh eval

set -euo pipefail

# Always run from the simulation directory in your project
cd ~/hulab/projects/mcDETECT/simulation

# ---------- Single-job modes ----------

# JOB + BLOCK: run one block for one scenario in this allocation
if [[ $# -eq 2 ]]; then
    JOB="$1"
    BLOCK="$2"
    if [[ ! "$JOB" =~ ^(A|B|C|all)$ ]]; then
        echo "Usage: sbatch run_SSAM.sh JOB BLOCK  (JOB=A|B|C|all, BLOCK=1..20)" >&2
        exit 1
    fi
    if ! [[ "$BLOCK" =~ ^[0-9]+$ ]] || (( BLOCK < 1 || BLOCK > 20 )); then
        echo "BLOCK must be an integer in [1,20], got '$BLOCK'" >&2
        exit 1
    fi
    module purge
    module load miniconda3
    eval "$(conda shell.bash hook)"
    conda activate ssam_hpc
    export PYTHONNOUSERSITE=1
    echo "Host: $(hostname)  Job: $JOB  Block: $BLOCK  PWD: $(pwd)"
    python3 run_SSAM.py --job "$JOB" --block "$BLOCK"
    echo "Job $JOB block $BLOCK finished at $(date)"
    exit 0
fi

# JOB only: run all 200 seeds for that scenario in one job (no blocks)
if [[ $# -eq 1 ]]; then
    JOB="$1"
    if [[ "$JOB" == "eval" ]]; then
        # Evaluation-only job: assumes all spheres have been generated by blocks.
        module purge
        module load miniconda3
        eval "$(conda shell.bash hook)"
        conda activate ssam_hpc
        export PYTHONNOUSERSITE=1
        echo "Host: $(hostname)  Eval-only run  PWD: $(pwd)"
        python3 run_SSAM.py
        echo "Evaluation finished at $(date)"
        exit 0
    fi
    if [[ ! "$JOB" =~ ^(A|B|C|all)$ ]]; then
        echo "Usage: sbatch run_SSAM.sh [A|B|C|all|eval]" >&2
        exit 1
    fi
    module purge
    module load miniconda3
    eval "$(conda shell.bash hook)"
    conda activate ssam_hpc
    export PYTHONNOUSERSITE=1
    echo "Host: $(hostname)  Job: $JOB  PWD: $(pwd)"
    python3 run_SSAM.py --job "$JOB"
    echo "Job $JOB finished at $(date)"
    exit 0
fi

# ---------- No args: submit 4×20 block jobs ----------

for JOB in A B C all; do
  for BLOCK in $(seq 1 20); do
    sbatch --job-name="SSAM_${JOB}_${BLOCK}" \
           --output="logs/SSAM_${JOB}_block${BLOCK}_%j.out" \
           --error="logs/SSAM_${JOB}_block${BLOCK}_%j.err" \
           --time=240:00:00 \
           --mem=200G \
           --cpus-per-task=16 \
           --partition=nodes \
           --mail-type=END,FAIL \
           --mail-user=cyuan36@emory.edu \
           "$0" "$JOB" "$BLOCK"
  done
done

echo "Submitted 4×20 block jobs (A,B,C,all; blocks 1–20). After they finish, run:"
echo "  sbatch run_SSAM.sh eval"